version: '3.8'

services:
  voice-notes-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voice-notes-api
    # Remove direct port exposure - access via nginx proxy
    expose:
      - "8000"
    volumes:
      # Mount Obsidian vault directory (update path as needed)
      - ${OBSIDIAN_VAULT_PATH:-./obsidian-vault}:/vault
      # Mount logs directory
      - ./logs:/app/logs
      # Mount app code for development hot-reload
      - ./app:/app/app:ro
    environment:
      - APP_NAME=Dialtone
      - APP_VERSION=0.1.0
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - OBSIDIAN_VAULT_PATH=/vault
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE:-52428800}  # 50MB
      - PROCESSING_TIMEOUT=${PROCESSING_TIMEOUT:-35}
      # Ollama Configuration
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama2:7b}
      - OLLAMA_TIMEOUT=${OLLAMA_TIMEOUT:-30}
      - OLLAMA_ENABLED=${OLLAMA_ENABLED:-true}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - dialtone-network
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434"  # Internal only - not exposed to host
    volumes:
      - ./ollama-models:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MODELS=/root/.ollama/models
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 12G
        reservations:
          cpus: '1'
          memory: 4G
    shm_size: 2G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    networks:
      - dialtone-network

  nginx:
    image: nginx:alpine
    container_name: dialtone-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./app/static:/var/www/html:ro
    networks:
      - dialtone-network
    depends_on:
      - voice-notes-api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M

networks:
  dialtone-network:
    driver: bridge